# CMake generated Testfile for 
# Source directory: /Users/useruser/Desktop/Thrift-Xcode/thrift/lib/c_glib/test
# Build directory: /Users/useruser/Desktop/Thrift-Xcode/lib/c_glib/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testserialization "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testserialization")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testserialization "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testserialization")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testserialization "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testserialization")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testserialization "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testserialization")
else()
  add_test(testserialization NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testapplicationexception "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testapplicationexception")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testapplicationexception "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testapplicationexception")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testapplicationexception "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testapplicationexception")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testapplicationexception "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testapplicationexception")
else()
  add_test(testapplicationexception NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testtransportsocket "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testtransportsocket")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testtransportsocket "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testtransportsocket")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testtransportsocket "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testtransportsocket")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testtransportsocket "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testtransportsocket")
else()
  add_test(testtransportsocket NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testbinaryprotocol "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testbinaryprotocol")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testbinaryprotocol "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testbinaryprotocol")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testbinaryprotocol "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testbinaryprotocol")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testbinaryprotocol "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testbinaryprotocol")
else()
  add_test(testbinaryprotocol NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testcompactprotocol "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testcompactprotocol")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testcompactprotocol "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testcompactprotocol")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testcompactprotocol "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testcompactprotocol")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testcompactprotocol "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testcompactprotocol")
else()
  add_test(testcompactprotocol NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testbufferedtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testbufferedtransport")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testbufferedtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testbufferedtransport")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testbufferedtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testbufferedtransport")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testbufferedtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testbufferedtransport")
else()
  add_test(testbufferedtransport NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testframedtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testframedtransport")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testframedtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testframedtransport")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testframedtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testframedtransport")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testframedtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testframedtransport")
else()
  add_test(testframedtransport NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testfdtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testfdtransport")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testfdtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testfdtransport")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testfdtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testfdtransport")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testfdtransport "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testfdtransport")
else()
  add_test(testfdtransport NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testmemorybuffer "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testmemorybuffer")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testmemorybuffer "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testmemorybuffer")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testmemorybuffer "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testmemorybuffer")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testmemorybuffer "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testmemorybuffer")
else()
  add_test(testmemorybuffer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testsimpleserver "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testsimpleserver")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testsimpleserver "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testsimpleserver")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testsimpleserver "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testsimpleserver")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testsimpleserver "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testsimpleserver")
else()
  add_test(testsimpleserver NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testdebugproto "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testdebugproto")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testdebugproto "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testdebugproto")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testdebugproto "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testdebugproto")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testdebugproto "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testdebugproto")
else()
  add_test(testdebugproto NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testoptionalrequired "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testoptionalrequired")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testoptionalrequired "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testoptionalrequired")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testoptionalrequired "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testoptionalrequired")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testoptionalrequired "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testoptionalrequired")
else()
  add_test(testoptionalrequired NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testthrifttest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testthrifttest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testthrifttest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testthrifttest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testthrifttest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testthrifttest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testthrifttest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testthrifttest")
else()
  add_test(testthrifttest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testthrifttestclient "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/testthrifttestclient")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testthrifttestclient "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/testthrifttestclient")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testthrifttestclient "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/testthrifttestclient")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testthrifttestclient "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/testthrifttestclient")
else()
  add_test(testthrifttestclient NOT_AVAILABLE)
endif()
