# CMake generated Testfile for 
# Source directory: /Users/useruser/Desktop/Thrift-Xcode/thrift/lib/cpp/test
# Build directory: /Users/useruser/Desktop/Thrift-Xcode/lib/cpp/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Benchmark "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/Benchmark")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Benchmark "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/Benchmark")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Benchmark "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/Benchmark")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Benchmark "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/Benchmark")
else()
  add_test(Benchmark NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(UnitTests "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/UnitTests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(UnitTests "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/UnitTests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(UnitTests "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/UnitTests")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(UnitTests "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/UnitTests")
else()
  add_test(UnitTests NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TInterruptTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/TInterruptTest" "--" "/Users/useruser/Desktop/Thrift-Xcode/thrift/lib/cpp/test/../../../test/keys")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TInterruptTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/TInterruptTest" "--" "/Users/useruser/Desktop/Thrift-Xcode/thrift/lib/cpp/test/../../../test/keys")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TInterruptTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/TInterruptTest" "--" "/Users/useruser/Desktop/Thrift-Xcode/thrift/lib/cpp/test/../../../test/keys")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TInterruptTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/TInterruptTest" "--" "/Users/useruser/Desktop/Thrift-Xcode/thrift/lib/cpp/test/../../../test/keys")
else()
  add_test(TInterruptTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TServerIntegrationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/TServerIntegrationTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TServerIntegrationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/TServerIntegrationTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TServerIntegrationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/TServerIntegrationTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TServerIntegrationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/TServerIntegrationTest")
else()
  add_test(TServerIntegrationTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/TransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/TransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/TransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/TransportTest")
else()
  add_test(TransportTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ZlibTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/ZlibTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ZlibTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/ZlibTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ZlibTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/ZlibTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ZlibTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/ZlibTest")
else()
  add_test(ZlibTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(AnnotationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/AnnotationTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(AnnotationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/AnnotationTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(AnnotationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/AnnotationTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(AnnotationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/AnnotationTest")
else()
  add_test(AnnotationTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EnumTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/EnumTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EnumTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/EnumTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EnumTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/EnumTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EnumTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/EnumTest")
else()
  add_test(EnumTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TFileTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/TFileTransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TFileTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/TFileTransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TFileTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/TFileTransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TFileTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/TFileTransportTest")
else()
  add_test(TFileTransportTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TFDTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/TFDTransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TFDTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/TFDTransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TFDTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/TFDTransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TFDTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/TFDTransportTest")
else()
  add_test(TFDTransportTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TPipedTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/TPipedTransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TPipedTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/TPipedTransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TPipedTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/TPipedTransportTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TPipedTransportTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/TPipedTransportTest")
else()
  add_test(TPipedTransportTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(AllProtocolsTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/AllProtocolsTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(AllProtocolsTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/AllProtocolsTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(AllProtocolsTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/AllProtocolsTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(AllProtocolsTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/AllProtocolsTest")
else()
  add_test(AllProtocolsTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DebugProtoTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/DebugProtoTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DebugProtoTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/DebugProtoTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DebugProtoTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/DebugProtoTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DebugProtoTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/DebugProtoTest")
else()
  add_test(DebugProtoTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(JSONProtoTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/JSONProtoTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(JSONProtoTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/JSONProtoTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(JSONProtoTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/JSONProtoTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(JSONProtoTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/JSONProtoTest")
else()
  add_test(JSONProtoTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(OptionalRequiredTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/OptionalRequiredTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(OptionalRequiredTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/OptionalRequiredTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(OptionalRequiredTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/OptionalRequiredTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(OptionalRequiredTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/OptionalRequiredTest")
else()
  add_test(OptionalRequiredTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(RecursiveTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/RecursiveTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(RecursiveTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/RecursiveTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(RecursiveTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/RecursiveTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(RecursiveTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/RecursiveTest")
else()
  add_test(RecursiveTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SpecializationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/SpecializationTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SpecializationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/SpecializationTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SpecializationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/SpecializationTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SpecializationTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/SpecializationTest")
else()
  add_test(SpecializationTest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(concurrency_test "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/concurrency_test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(concurrency_test "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/concurrency_test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(concurrency_test "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/concurrency_test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(concurrency_test "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/concurrency_test")
else()
  add_test(concurrency_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(link_test "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/link_test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(link_test "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/link_test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(link_test "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/link_test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(link_test "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/link_test")
else()
  add_test(link_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(processor_test "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/processor_test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(processor_test "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/processor_test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(processor_test "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/processor_test")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(processor_test "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/processor_test")
else()
  add_test(processor_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(TNonblockingServerTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Debug/TNonblockingServerTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(TNonblockingServerTest "/Users/useruser/Desktop/Thrift-Xcode/bin/Release/TNonblockingServerTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(TNonblockingServerTest "/Users/useruser/Desktop/Thrift-Xcode/bin/MinSizeRel/TNonblockingServerTest")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(TNonblockingServerTest "/Users/useruser/Desktop/Thrift-Xcode/bin/RelWithDebInfo/TNonblockingServerTest")
else()
  add_test(TNonblockingServerTest NOT_AVAILABLE)
endif()
